# Generated by Django 5.2.1 on 2025-05-31 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='discriprion',
            new_name='discription',
        ),
    ]
